import {getCurrentUser,jsonResponse} from '../lib/auth.js';
import {signJWT,verifyJWT} from '../lib/crypto.js';
import {ensureBudgetSchema} from './budget.js';
import {ensureProjectWorkflowSchema} from './project-workflow.js';
import {sumMoney} from '../lib/project-finance.js';
const SCOPES={requests:['project_expenses','คำขอ / รายการเบิกจ่าย'],projects:['projects','โครงการ'],leave:['leave_requests','คำขอลา'],tasks:['tasks','งานที่มอบหมาย'],maintenance:['maintenance_requests','แจ้งซ่อม'],income:['budget_income','รายรับ'],documents:['documents','เอกสาร']};
const ready=new WeakSet(),quote=s=>'"'+String(s).replaceAll('"','""')+'"';
const chunks=(a,size=60)=>Array.from({length:Math.ceil(a.length/size)},(_,i)=>a.slice(i*size,i*size+size));
async function ensure(env){if(ready.has(env.DB))return;await ensureBudgetSchema(env);await ensureProjectWorkflowSchema(env);await env.DB.batch([
 env.DB.prepare(`CREATE TABLE IF NOT EXISTS admin_cleanup_archive(id TEXT PRIMARY KEY,user_id INTEGER NOT NULL,scope TEXT NOT NULL,reason TEXT NOT NULL,snapshot TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT(datetime('now')))`),
 env.DB.prepare('CREATE TABLE IF NOT EXISTS admin_cleanup_assert(valid INTEGER NOT NULL CHECK(valid=1))'),
 env.DB.prepare('CREATE TABLE IF NOT EXISTS admin_cleanup_sessions(token TEXT PRIMARY KEY,user_id INTEGER NOT NULL,expires_at INTEGER NOT NULL)')]);ready.add(env.DB);}
async function capability(env,user,token,purpose){const p=await verifyJWT(token||'',env.JWT_SECRET);if(!p||Number(p.sub)!==Number(user.id)||p.purpose!==purpose)return null;
 if(purpose==='admin_cleanup'&&!await env.DB.prepare('SELECT 1 FROM admin_cleanup_sessions WHERE token=? AND user_id=? AND expires_at>?').bind(token,user.id,Math.floor(Date.now()/1000)).first())return null;return p;}
function selection(body){return SCOPES[body?.scope]&&Array.isArray(body.ids)&&body.ids.length>0&&body.ids.length<=100&&body.ids.every(x=>Number.isSafeInteger(x)&&x>0)&&new Set(body.ids).size===body.ids.length;}
async function catalog(env){const {results}=await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE 'admin_cleanup_%' AND name NOT LIKE '_cf_%'").all();const meta={};for(const {name} of results){const cols=(await env.DB.prepare(`PRAGMA table_info(${quote(name)})`).all()).results,fks=(await env.DB.prepare(`PRAGMA foreign_key_list(${quote(name)})`).all()).results;meta[name]={cols:cols.map(c=>c.name),pk:cols.filter(c=>c.pk).sort((a,b)=>a.pk-b.pk).map(c=>c.name),fks};}return meta;}
async function plan(env,scope,ids){const meta=await catalog(env),rows=new Map(),root=SCOPES[scope][0];
 const add=async(table,column,values)=>{if(!meta[table]||!values.length)return false;let changed=false;for(const batch of chunks([...new Set(values)])){const found=(await env.DB.prepare(`SELECT * FROM ${quote(table)} WHERE ${quote(column)} IN (${batch.map(()=>'?').join(',')})`).bind(...batch).all()).results;const entries=rows.get(table)||new Map();for(const r of found){const key=JSON.stringify(meta[table].pk.map(k=>r[k]));if(!entries.has(key)){entries.set(key,r);changed=true;}}if(entries.size)rows.set(table,entries);}return changed;};
 await add(root,'id',ids);if((rows.get(root)?.size||0)!==ids.length)throw Object.assign(new Error('มีรายการถูกลบไปแล้ว กรุณาเลือกใหม่'),{status:409});
 let changed=true;while(changed){changed=false;for(const [child,m] of Object.entries(meta))for(const fk of m.fks){const parents=rows.get(fk.table);if(parents)changed=await add(child,fk.from,[...parents.values()].map(r=>r[fk.to||'id']).filter(v=>v!=null))||changed;}
 const supporting=rows.get('budget_supporting_documents');if(supporting)changed=await add('documents','id',[...supporting.values()].map(r=>r.native_document_id))||changed;
 const attachments={project_expenses:['project_expense'],documents:['document'],maintenance_requests:['maintenance_request','maintenance_before','maintenance_after'],maintenance_updates:['maintenance_update']};
 for(const [table,types] of Object.entries(attachments)){if(!rows.has(table)||!meta.file_attachments)continue;for(const batch of chunks([...rows.get(table).values()].map(r=>r.id))){const found=(await env.DB.prepare(`SELECT * FROM file_attachments WHERE entity_type IN (${types.map(()=>'?').join(',')}) AND entity_id IN (${batch.map(()=>'?').join(',')})`).bind(...types,...batch).all()).results;const entries=rows.get('file_attachments')||new Map();for(const r of found)if(!entries.has(String(r.id))){entries.set(String(r.id),r);changed=true;}if(entries.size)rows.set('file_attachments',entries);}}
 if([...rows.values()].reduce((n,m)=>n+m.size,0)>5000)throw Object.assign(new Error('รายการที่เกี่ยวข้องมากเกินไป กรุณาลบเป็นชุดย่อย'),{status:400});}
 const tables=Object.fromEntries([...rows].sort(([a],[b])=>a.localeCompare(b)).map(([t,m])=>[t,[...m.values()].sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)))]));
 return {meta,tables,scope,ids:[...ids].sort((a,b)=>a-b)};}
async function digest(plan){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify({scope:plan.scope,ids:plan.ids,tables:plan.tables})));return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function label(r){return r.name||r.title||r.request_no||r.request_purpose||r.description||r.source_name||r.reason||r.document_no||`รายการ ${r.id}`;}
function impact(p){const e=p.tables.project_expenses||[],projects=p.tables.projects||[];return {tables:Object.entries(p.tables).map(([table,r])=>({table,count:r.length})),records:p.tables[SCOPES[p.scope][0]].map(r=>({id:r.id,title:label(r),status:r.status||'',date:r.created_at||r.expense_date||r.start_date||r.received_date||''})),paid_removed:sumMoney(e.filter(r=>r.status==='paid').map(r=>r.amount)),reserved_removed:sumMoney(e.filter(r=>['pending','approved'].includes(r.status)).map(r=>r.amount)),allocation_removed:sumMoney(projects.map(r=>r.budget_amount)),file_count:(p.tables.file_attachments||[]).length};}
export async function handleAdminCleanup(request,env,pathname,method){if(!pathname.startsWith('/api/admin/cleanup'))return null;const user=await getCurrentUser(request,env);if(!user)return jsonResponse({error:'กรุณาเข้าสู่ระบบ'},401);if(user.role!=='superadmin')return jsonResponse({error:'Avada Kedavra ใช้ได้เฉพาะผู้ดูแลระบบ'},403);await ensure(env);
 try{const body=method==='GET'?{}:await request.json().catch(()=>({}));
 if(pathname==='/api/admin/cleanup'&&method==='GET')return jsonResponse({scopes:Object.entries(SCOPES).map(([key,[table,label]])=>({key,label})),expires_in:900},200,{'Cache-Control':'no-store'});
 if(pathname==='/api/admin/cleanup/session'&&method==='POST'){const token=await signJWT({sub:user.id,purpose:'admin_cleanup',nonce:crypto.randomUUID()},env.JWT_SECRET,900);await env.DB.prepare('INSERT OR REPLACE INTO admin_cleanup_sessions(token,user_id,expires_at) VALUES(?,?,?)').bind(token,user.id,Math.floor(Date.now()/1000)+900).run();return jsonResponse({token,expires_at:Date.now()+900000});}
 if(pathname==='/api/admin/cleanup/session'&&method==='DELETE'){await env.DB.prepare('DELETE FROM admin_cleanup_sessions WHERE token=? AND user_id=?').bind(body.mode_token||'',user.id).run();return jsonResponse({ok:true});}
 const modeToken=method==='GET'?request.headers.get('X-Cleanup-Token'):body.mode_token;if(!await capability(env,user,modeToken,'admin_cleanup'))return jsonResponse({error:'กรุณาเปิดโหมด Avada Kedavra ใหม่ (หมดเวลาใน 15 นาที)'},403);
 if(pathname==='/api/admin/cleanup/records'&&method==='GET'){const params=new URL(request.url).searchParams,scope=params.get('scope'),term=(params.get('search')||'').trim().slice(0,150),page=Math.max(1,Number(params.get('page'))||1);if(!SCOPES[scope])return jsonResponse({error:'ส่วนข้อมูลไม่ถูกต้อง'},400);const table=SCOPES[scope][0],cols=(await env.DB.prepare(`PRAGMA table_info(${quote(table)})`).all()).results.map(x=>x.name);const fields=['id','name','title','request_no','description','reason','request_purpose','source_name','created_at','start_date','fiscal_year','department'].filter(c=>cols.includes(c));const where=term?` WHERE (${fields.map(c=>`instr(lower(CAST(${quote(c)} AS TEXT)),lower(?))>0`).join(' OR ')})`:'';const args=term?fields.map(()=>term):[];const total=await env.DB.prepare(`SELECT COUNT(*) n FROM ${quote(table)}${where}`).bind(...args).first();const records=(await env.DB.prepare(`SELECT * FROM ${quote(table)}${where} ORDER BY id DESC LIMIT 50 OFFSET ?`).bind(...args,(page-1)*50).all()).results;return jsonResponse({total:total.n,page,records:records.map(r=>({id:r.id,title:label(r),status:r.status||'',year:r.fiscal_year||'',department:r.department||'',amount:r.amount??r.budget_amount??null,date:r.created_at||r.expense_date||r.start_date||r.received_date||''}))},200,{'Cache-Control':'no-store'});}
 if(pathname==='/api/admin/cleanup/preview'&&method==='POST'){if(!selection(body))return jsonResponse({error:'เลือกส่วนและรายการ 1–100 รายการ'},400);const p=await plan(env,body.scope,body.ids);const preview_token=await signJWT({sub:user.id,purpose:'cleanup_preview',scope:p.scope,ids:p.ids,digest:await digest(p)},env.JWT_SECRET,300);return jsonResponse({preview_token,...impact(p)});}
 if(pathname==='/api/admin/cleanup/delete'&&method==='POST'){const preview=await capability(env,user,body.preview_token,'cleanup_preview');if(!preview||body.confirmation!=='Avada Kedavra'||!String(body.reason||'').trim())return jsonResponse({error:'ตรวจสอบรายการ ระบุเหตุผล และพิมพ์ Avada Kedavra เพื่อยืนยัน'},400);const p=await plan(env,preview.scope,preview.ids);if(await digest(p)!==preview.digest)return jsonResponse({error:'ข้อมูลเปลี่ยนหลังตรวจสอบ กรุณาตรวจสอบรายการใหม่ก่อนลบ'},409);
 if(new TextEncoder().encode(JSON.stringify(p.tables)).length>1500000)return jsonResponse({error:'ข้อมูลสำรองใหญ่เกินไป กรุณาลบเป็นชุดย่อย'},400);
 const archiveId=crypto.randomUUID(),statements=[];
 // Check every archived row again inside the same transaction before making any change.
 for(const [table,records] of Object.entries(p.tables)){const cols=p.meta[table].cols;for(const batch of chunks(records,Math.max(1,Math.floor(90/cols.length)))){const conditions=[],args=[];for(const row of batch){conditions.push('('+cols.map(c=>`${quote(c)} IS ?`).join(' AND ')+')');args.push(...cols.map(c=>row[c]));}statements.push(env.DB.prepare(`INSERT INTO admin_cleanup_assert(valid) SELECT CASE WHEN COUNT(*)=? THEN 1 ELSE 0 END FROM ${quote(table)} WHERE ${conditions.join(' OR ')}`).bind(batch.length,...args));}}
 // Refuse new dependent rows that appeared after the preview, rather than cascading unarchived data.
 for(const [child,m] of Object.entries(p.meta))for(const fk of m.fks){const parents=p.tables[fk.table];if(!parents)continue;const values=[...new Set(parents.map(r=>r[fk.to||'id']).filter(v=>v!=null))];for(const batch of chunks(values)){const count=(p.tables[child]||[]).filter(r=>batch.includes(r[fk.from])).length;statements.push(env.DB.prepare(`INSERT INTO admin_cleanup_assert(valid) SELECT CASE WHEN COUNT(*)=? THEN 1 ELSE 0 END FROM ${quote(child)} WHERE ${quote(fk.from)} IN (${batch.map(()=>'?').join(',')})`).bind(count,...batch));}}
 const attachmentTypes={project_expenses:['project_expense'],documents:['document'],maintenance_requests:['maintenance_request','maintenance_before','maintenance_after'],maintenance_updates:['maintenance_update']};
 for(const [table,types] of Object.entries(attachmentTypes)){if(!p.tables[table]||!p.meta.file_attachments)continue;for(const batch of chunks(p.tables[table].map(r=>r.id))){const count=(p.tables.file_attachments||[]).filter(r=>types.includes(r.entity_type)&&batch.includes(r.entity_id)).length;statements.push(env.DB.prepare(`INSERT INTO admin_cleanup_assert(valid) SELECT CASE WHEN COUNT(*)=? THEN 1 ELSE 0 END FROM file_attachments WHERE entity_type IN (${types.map(()=>'?').join(',')}) AND entity_id IN (${batch.map(()=>'?').join(',')})`).bind(count,...types,...batch));}}
 const expenses=(p.tables.project_expenses||[]).map(r=>r.id);for(const batch of chunks(expenses))statements.push(env.DB.prepare(`INSERT INTO admin_cleanup_expense_guard(expense_id) VALUES ${batch.map(()=>'(?)').join(',')}`).bind(...batch));
 statements.push(env.DB.prepare('INSERT INTO admin_cleanup_archive(id,user_id,scope,reason,snapshot) VALUES(?,?,?,?,?)').bind(archiveId,user.id,p.scope,String(body.reason).trim().slice(0,1500),JSON.stringify(p.tables)));
 const pending=new Set(Object.keys(p.tables)),order=[];while(pending.size){let next=[...pending].find(t=>![...pending].some(child=>child!==t&&p.meta[child].fks.some(f=>f.table===t)));if(!next)throw Object.assign(new Error('ข้อมูลมีความสัมพันธ์วนกัน กรุณาลบรายการย่อยก่อน'),{status:409});order.push(next);pending.delete(next);}
 for(const table of order){const pk=p.meta[table].pk;if(!pk.length)throw new Error('missing primary key');for(const batch of chunks(p.tables[table],Math.max(1,Math.floor(90/pk.length)))){const where=batch.map(()=>`(${pk.map(k=>`${quote(k)} IS ?`).join(' AND ')})`).join(' OR ');statements.push(env.DB.prepare(`DELETE FROM ${quote(table)} WHERE ${where}`).bind(...batch.flatMap(r=>pk.map(k=>r[k]))));}}
 for(const batch of chunks(expenses))statements.push(env.DB.prepare(`DELETE FROM admin_cleanup_expense_guard WHERE expense_id IN (${batch.map(()=>'?').join(',')})`).bind(...batch));
 statements.push(env.DB.prepare('DELETE FROM admin_cleanup_assert'));
 statements.push(env.DB.prepare("INSERT INTO audit_logs(user_id,action,resource,resource_id,details,ip_address) VALUES(?,'test_cleanup','admin_cleanup',?,?,?)").bind(user.id,archiveId,JSON.stringify({scope:p.scope,ids:p.ids,reason:String(body.reason).slice(0,1500),impact:impact(p)}),request.headers.get('CF-Connecting-IP')));
 await env.DB.batch(statements);return jsonResponse({ok:true,archive_id:archiveId,deleted:preview.ids.length,message:'ลบข้อมูลที่เลือกและปรับยอดทั้งระบบแล้ว'});}
 return jsonResponse({error:'ไม่พบคำสั่ง'},404);
 }catch(e){return jsonResponse({error:e.status?e.message:'ลบไม่สำเร็จ ข้อมูลยังอยู่ครบ กรุณาตรวจสอบใหม่'},e.status||409);}}
