import { getCurrentUser, isAdmin, jsonResponse } from "../lib/auth.js";

const STATUSES=["draft","pending","approved","paid","rejected","cancelled"];
const CATEGORIES=["materials","equipment","services","compensation","utilities","travel","food","opening_balance","other"];
const PAYMENT_METHODS=["transfer","cash","cheque","other"];
let schemaReady=false;
const clean=(v,n=500)=>String(v??"").trim().slice(0,n)||null;
function validDate(v){const s=String(v||"");if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const [y,m,d]=s.split("-").map(Number),x=new Date(Date.UTC(y,m-1,d));return x.getUTCFullYear()===y&&x.getUTCMonth()===m-1&&x.getUTCDate()===d}
function fiscalYear(date=new Date().toISOString().slice(0,10)){const [y,m]=date.split("-").map(Number);return y+(m>=10?544:543)}
async function addColumn(env,table,name,definition){try{await env.DB.prepare(`ALTER TABLE ${table} ADD COLUMN ${name} ${definition}`).run()}catch(e){if(!String(e?.message||e).toLowerCase().includes("duplicate column"))throw e}}

export async function ensureBudgetSchema(env){
  if(schemaReady)return;
  await env.DB.batch([
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS budget_income(id INTEGER PRIMARY KEY AUTOINCREMENT,fiscal_year INTEGER NOT NULL,received_date TEXT NOT NULL,document_no TEXT,source_name TEXT NOT NULL,source_type TEXT NOT NULL DEFAULT 'other',amount REAL NOT NULL CHECK(amount>0),notes TEXT,created_by INTEGER NOT NULL REFERENCES users(id),created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')))`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS budget_counters(fiscal_year INTEGER PRIMARY KEY,last_number INTEGER NOT NULL DEFAULT 0)`),
    env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_budget_income_year ON budget_income(fiscal_year,received_date DESC)")
  ]);
  await addColumn(env,"projects","fiscal_year","INTEGER");
  for(const [name,definition] of [["request_no","TEXT"],["fiscal_year","INTEGER"],["submitted_at","TEXT"],["review_note","TEXT"],["payment_no","TEXT"],["payment_method","TEXT"],["payment_date","TEXT"]])await addColumn(env,"project_expenses",name,definition);
  await env.DB.batch([
    env.DB.prepare("CREATE UNIQUE INDEX IF NOT EXISTS idx_project_expenses_request_no ON project_expenses(request_no) WHERE request_no IS NOT NULL"),
    env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_project_expenses_fiscal_year ON project_expenses(fiscal_year,status,expense_date DESC)"),
    env.DB.prepare(`UPDATE project_expenses SET fiscal_year=CAST(strftime('%Y',expense_date) AS INTEGER)+CASE WHEN CAST(strftime('%m',expense_date) AS INTEGER)>=10 THEN 544 ELSE 543 END WHERE fiscal_year IS NULL`),
    env.DB.prepare("UPDATE project_expenses SET submitted_at=created_at WHERE status IN ('pending','approved','paid','rejected') AND submitted_at IS NULL"),
    env.DB.prepare("UPDATE project_expenses SET payment_date=substr(paid_at,1,10) WHERE status='paid' AND payment_date IS NULL"),
    env.DB.prepare(`UPDATE projects SET fiscal_year=CAST(strftime('%Y',COALESCE(created_at,datetime('now'))) AS INTEGER)+CASE WHEN CAST(strftime('%m',COALESCE(created_at,datetime('now'))) AS INTEGER)>=10 THEN 544 ELSE 543 END WHERE fiscal_year IS NULL`)
  ]);
  schemaReady=true;
}
async function user(request,env){const u=await getCurrentUser(request,env);return u?.role?u:null}
async function owner(env,u,id){if(isAdmin(u))return true;return !!(await env.DB.prepare("SELECT 1 FROM project_owners WHERE project_id=? AND user_id=?").bind(id,u.id).first())}
async function requestNo(env,year){const row=await env.DB.prepare(`INSERT INTO budget_counters(fiscal_year,last_number) VALUES(?,1) ON CONFLICT(fiscal_year) DO UPDATE SET last_number=last_number+1 RETURNING last_number`).bind(year).first();return `BUD-${year}-${String(row.last_number).padStart(4,"0")}`}
async function audit(env,u,action,id,details,request){await env.DB.prepare(`INSERT INTO audit_logs(user_id,action,resource,resource_id,details,ip_address) VALUES(?,?,?,?,?,?)`).bind(u.id,action,"budget_request",id,JSON.stringify(details||{}),request.headers.get("CF-Connecting-IP")||null).run()}

async function overview(request,env){
  const u=await user(request,env);if(!u)return jsonResponse({error:"กรุณาเข้าสู่ระบบ"},401);
  const year=Number(new URL(request.url).searchParams.get("fiscal_year"))||fiscalYear();
  const [summary,incomes,projects,requests,statusRows,audits]=await Promise.all([
    env.DB.prepare(`SELECT COALESCE((SELECT SUM(budget_amount) FROM projects WHERE status<>'cancelled' AND fiscal_year=?),0) total_budget,COALESCE((SELECT SUM(amount) FROM project_expenses WHERE fiscal_year=? AND status='pending'),0) pending_amount,COALESCE((SELECT SUM(amount) FROM project_expenses WHERE fiscal_year=? AND status='approved'),0) approved_amount,COALESCE((SELECT SUM(amount) FROM project_expenses WHERE fiscal_year=? AND status='paid'),0) paid_amount,COALESCE((SELECT SUM(amount) FROM budget_income WHERE fiscal_year=?),0) income_amount`).bind(year,year,year,year,year).first(),
    env.DB.prepare(`SELECT i.*,u.full_name creator_name FROM budget_income i LEFT JOIN users u ON u.id=i.created_by WHERE i.fiscal_year=? ORDER BY i.received_date DESC,i.id DESC`).bind(year).all(),
    env.DB.prepare(`SELECT p.id,p.department,p.name,p.budget_amount,p.spent_amount,p.status,p.description,COALESCE(SUM(CASE WHEN e.fiscal_year=? AND e.status='pending' THEN e.amount ELSE 0 END),0) pending_amount,COALESCE(SUM(CASE WHEN e.fiscal_year=? AND e.status='approved' THEN e.amount ELSE 0 END),0) approved_amount,GROUP_CONCAT(DISTINCT u.full_name) owner_names FROM projects p LEFT JOIN project_expenses e ON e.project_id=p.id LEFT JOIN project_owners po ON po.project_id=p.id LEFT JOIN users u ON u.id=po.user_id WHERE p.status<>'cancelled' AND p.fiscal_year=? GROUP BY p.id ORDER BY p.department,p.name`).bind(year,year,year).all(),
    env.DB.prepare(`SELECT e.*,p.name project_name,p.department,creator.full_name requester_name,approver.full_name approver_name,a.id attachment_id,a.file_name attachment_name FROM project_expenses e JOIN projects p ON p.id=e.project_id LEFT JOIN users creator ON creator.id=e.created_by LEFT JOIN users approver ON approver.id=e.approved_by LEFT JOIN file_attachments a ON a.entity_type='project_expense' AND a.entity_id=e.id WHERE e.fiscal_year=? ORDER BY CASE e.status WHEN 'pending' THEN 0 WHEN 'approved' THEN 1 WHEN 'draft' THEN 2 ELSE 3 END,e.created_at DESC,e.id DESC`).bind(year).all(),
    env.DB.prepare(`SELECT status,COUNT(*) item_count,COALESCE(SUM(amount),0) total_amount FROM project_expenses WHERE fiscal_year=? GROUP BY status`).bind(year).all(),
    env.DB.prepare(`SELECT a.*,u.full_name user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id WHERE a.resource='budget_request' ORDER BY a.created_at DESC LIMIT 80`).all()
  ]);
  const totals=Object.fromEntries(STATUSES.map(s=>[s,{item_count:0,total_amount:0}]));for(const r of statusRows.results)totals[r.status]={item_count:Number(r.item_count),total_amount:Number(r.total_amount)};
  const num=x=>Number(x||0),total=num(summary.total_budget),approved=num(summary.approved_amount),paid=num(summary.paid_amount);
  return jsonResponse({fiscal_year:year,summary:{...summary,total_budget:total,pending_amount:num(summary.pending_amount),approved_amount:approved,paid_amount:paid,income_amount:num(summary.income_amount),available_amount:total-approved-paid},status_totals:totals,projects:projects.results.map(r=>({...r,budget_amount:num(r.budget_amount),spent_amount:num(r.spent_amount),pending_amount:num(r.pending_amount),approved_amount:num(r.approved_amount)})),requests:requests.results.map(r=>({...r,amount:num(r.amount),can_edit:isAdmin(u)||(r.created_by===u.id&&["draft","pending"].includes(r.status))})),incomes:incomes.results.map(r=>({...r,amount:num(r.amount)})),audit:audits.results,permissions:{can_approve:isAdmin(u),can_manage_income:isAdmin(u),role:u.role}})
}
async function createRequest(request,env){
  const u=await user(request,env);if(!u)return jsonResponse({error:"กรุณาเข้าสู่ระบบ"},401);const b=await request.json().catch(()=>null);if(!b)return jsonResponse({error:"รูปแบบข้อมูลไม่ถูกต้อง"},400);
  const projectId=Number(b.project_id),p=await env.DB.prepare("SELECT id,budget_amount,fiscal_year FROM projects WHERE id=? AND status<>'cancelled'").bind(projectId).first();if(!p)return jsonResponse({error:"ไม่พบโครงการที่เลือก"},404);if(!(await owner(env,u,projectId)))return jsonResponse({error:"คุณไม่ได้เป็นผู้รับผิดชอบโครงการนี้"},403);
  const date=String(b.expense_date||""),amount=Number(b.amount),description=clean(b.description,1000);if(!validDate(date)||!description||!Number.isFinite(amount)||amount<=0)return jsonResponse({error:"กรุณากรอกวันที่ วัตถุประสงค์ และจำนวนเงินให้ถูกต้อง"},400);
  const year=Number(b.fiscal_year)||Number(p.fiscal_year)||fiscalYear(date);if(!Number.isInteger(year)||year<2500||year>3000)return jsonResponse({error:"ปีงบประมาณไม่ถูกต้อง"},400);if(Number(p.fiscal_year)!==year)return jsonResponse({error:`โครงการนี้อยู่ในปีงบประมาณ ${p.fiscal_year}`},409);
  const no=await requestNo(env,year),status=b.save_as_draft?"draft":"pending",category=CATEGORIES.includes(b.category)&&b.category!=="opening_balance"?b.category:"other";
  const result=await env.DB.prepare(`INSERT INTO project_expenses(project_id,expense_date,document_no,category,description,payee,amount,status,notes,created_by,request_no,fiscal_year,submitted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(projectId,date,clean(b.document_no,100),category,description,clean(b.payee,250),amount,status,clean(b.notes,1000),u.id,no,year,status==="pending"?new Date().toISOString():null).run();
  await audit(env,u,status==="draft"?"draft":"submit",result.meta.last_row_id,{request_no:no,project_id:projectId,amount},request);return jsonResponse({id:result.meta.last_row_id,request_no:no},201)
}
async function updateRequest(request,env,id){
  const u=await user(request,env);if(!u)return jsonResponse({error:"กรุณาเข้าสู่ระบบ"},401);const row=await env.DB.prepare("SELECT * FROM project_expenses WHERE id=?").bind(id).first();if(!row)return jsonResponse({error:"ไม่พบคำขอ"},404);if(!isAdmin(u)&&row.created_by!==u.id)return jsonResponse({error:"ไม่มีสิทธิ์แก้ไขคำขอนี้"},403);if(!["draft","pending"].includes(row.status))return jsonResponse({error:"คำขอที่ผ่านการพิจารณาแล้วแก้ไขไม่ได้"},409);
  const b=await request.json().catch(()=>null),amount=Number(b?.amount);if(!b||!validDate(b.expense_date)||!clean(b.description,1000)||!Number.isFinite(amount)||amount<=0)return jsonResponse({error:"กรุณากรอกข้อมูลให้ถูกต้อง"},400);const category=CATEGORIES.includes(b.category)&&b.category!=="opening_balance"?b.category:"other";
  await env.DB.prepare(`UPDATE project_expenses SET expense_date=?,document_no=?,category=?,description=?,payee=?,amount=?,notes=?,updated_at=datetime('now') WHERE id=?`).bind(b.expense_date,clean(b.document_no,100),category,clean(b.description,1000),clean(b.payee,250),amount,clean(b.notes,1000),id).run();await audit(env,u,"edit",id,{amount},request);return jsonResponse({ok:true})
}
async function action(request,env,id){
  const u=await user(request,env);if(!u)return jsonResponse({error:"กรุณาเข้าสู่ระบบ"},401);const b=await request.json().catch(()=>null),act=b?.action,row=await env.DB.prepare(`SELECT e.*,p.budget_amount FROM project_expenses e JOIN projects p ON p.id=e.project_id WHERE e.id=?`).bind(id).first();if(!row)return jsonResponse({error:"ไม่พบคำขอ"},404);
  if(act==="submit"){if(!(await owner(env,u,row.project_id))||row.status!=="draft")return jsonResponse({error:"ส่งอนุมัติได้เฉพาะคำขอร่าง"},409);await env.DB.prepare("UPDATE project_expenses SET status='pending',submitted_at=datetime('now'),updated_at=datetime('now') WHERE id=?").bind(id).run()}
  else{if(!["approve","reject","pay","cancel"].includes(act))return jsonResponse({error:"คำสั่งไม่ถูกต้อง"},400);if(!isAdmin(u))return jsonResponse({error:"เฉพาะผู้บริหาร/ผู้ดูแลระบบเท่านั้น"},403);
    if(act==="approve"){if(row.status!=="pending")return jsonResponse({error:"อนุมัติได้เฉพาะคำขอที่รอตรวจสอบ"},409);const c=await env.DB.prepare(`SELECT COALESCE(SUM(amount),0) total FROM project_expenses WHERE project_id=? AND id<>? AND status IN('approved','paid')`).bind(row.project_id,id).first(),available=Number(row.budget_amount||0)-Number(c.total||0);if(Number(row.amount)>available)return jsonResponse({error:`วงเงินโครงการไม่พอ คงเหลือ ${available.toLocaleString("th-TH")} บาท`},409);await env.DB.prepare(`UPDATE project_expenses SET status='approved',approved_by=?,approved_at=datetime('now'),review_note=?,updated_at=datetime('now') WHERE id=?`).bind(u.id,clean(b.review_note,1000),id).run()}
    if(act==="reject"){if(row.status!=="pending")return jsonResponse({error:"ไม่อนุมัติได้เฉพาะคำขอที่รอตรวจสอบ"},409);if(!clean(b.review_note,1000))return jsonResponse({error:"กรุณาระบุเหตุผล"},400);await env.DB.prepare(`UPDATE project_expenses SET status='rejected',approved_by=?,approved_at=datetime('now'),review_note=?,updated_at=datetime('now') WHERE id=?`).bind(u.id,clean(b.review_note,1000),id).run()}
    if(act==="pay"){if(row.status!=="approved")return jsonResponse({error:"ต้องอนุมัติก่อนยืนยันจ่าย"},409);const no=clean(b.payment_no,100),date=String(b.payment_date||""),method=PAYMENT_METHODS.includes(b.payment_method)?b.payment_method:null;if(!no||!validDate(date)||!method)return jsonResponse({error:"กรุณาระบุเลขที่จ่าย วันที่ และวิธีจ่าย"},400);await env.DB.prepare(`UPDATE project_expenses SET status='paid',payment_no=?,payment_date=?,payment_method=?,paid_at=datetime('now'),updated_at=datetime('now') WHERE id=?`).bind(no,date,method,id).run()}
    if(act==="cancel"){if(["paid","cancelled"].includes(row.status))return jsonResponse({error:"รายการนี้ยกเลิกไม่ได้"},409);await env.DB.prepare(`UPDATE project_expenses SET status='cancelled',review_note=?,updated_at=datetime('now') WHERE id=?`).bind(clean(b.review_note,1000),id).run()}}
  await audit(env,u,act,id,{from:row.status,payment_no:clean(b.payment_no,100),review_note:clean(b.review_note,1000)},request);return jsonResponse({ok:true})
}
async function createIncome(request,env){const u=await user(request,env);if(!u)return jsonResponse({error:"กรุณาเข้าสู่ระบบ"},401);if(!isAdmin(u))return jsonResponse({error:"เฉพาะผู้บริหาร/ผู้ดูแลระบบเท่านั้น"},403);const b=await request.json().catch(()=>null),amount=Number(b?.amount);if(!b||!validDate(b.received_date)||!clean(b.source_name,300)||!Number.isFinite(amount)||amount<=0)return jsonResponse({error:"กรุณากรอกวันที่ แหล่งเงิน และจำนวนเงิน"},400);const year=Number(b.fiscal_year)||fiscalYear(b.received_date),result=await env.DB.prepare(`INSERT INTO budget_income(fiscal_year,received_date,document_no,source_name,source_type,amount,notes,created_by) VALUES(?,?,?,?,?,?,?,?)`).bind(year,b.received_date,clean(b.document_no,100),clean(b.source_name,300),clean(b.source_type,100)||"other",amount,clean(b.notes,1000),u.id).run();return jsonResponse({id:result.meta.last_row_id},201)}

export async function handleBudgetRoute(request,env,pathname,method){if(!pathname.startsWith("/api/budget"))return null;await ensureBudgetSchema(env);if(pathname==="/api/budget/overview"&&method==="GET")return overview(request,env);if(pathname==="/api/budget/requests"&&method==="POST")return createRequest(request,env);if(pathname==="/api/budget/income"&&method==="POST")return createIncome(request,env);let m=pathname.match(/^\/api\/budget\/requests\/(\d+)$/);if(m&&method==="PATCH")return updateRequest(request,env,Number(m[1]));m=pathname.match(/^\/api\/budget\/requests\/(\d+)\/action$/);if(m&&method==="POST")return action(request,env,Number(m[1]));return jsonResponse({error:"ไม่พบ endpoint งบประมาณนี้"},404)}
