import test from 'node:test';
import {handleAdminCleanup} from '../src/routes/admin-cleanup.js';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { signJWT } from '../src/lib/crypto.js';
import { ensureBudgetSchema, handleBudgetRoute } from '../src/routes/budget.js';
import worker from '../src/index.js';
import { handleProjectWorkflowRoute, notifyBudgetSupportingDocument, canAccessBudgetSupportingDocument, projectFundingSummary } from '../src/routes/project-workflow.js';

const secret='project-workflow-tests';
async function fixture(){
  const raw=new DatabaseSync(':memory:');raw.exec(readFileSync(new URL('../schema.sql',import.meta.url),'utf8'));
  raw.exec(`INSERT INTO users(id,email,password_hash,password_salt,full_name,role) VALUES
    (1,'admin@test','x','x','ผู้ดูแล','superadmin'),(2,'owner@test','x','x','เจ้าของ','teacher'),
    (3,'finance@test','x','x','การเงิน','staff'),(4,'other@test','x','x','ครูอื่น','teacher'),(5,'co-owner@test','x','x','เจ้าของร่วม','teacher');
    INSERT INTO projects(id,department,name,budget_amount,fiscal_year,created_by,funding_type) VALUES
    (10,'academic','อ่านคล่อง',1000,2570,1,'subsidy'),(11,'general','เรียนฟรี',2000,2570,1,'free_education'),
    (12,'budget','งานรายได้',3000,2570,1,'school_income'),(13,'personnel','โครงการเดิม',400,2570,1,NULL);
    INSERT INTO project_owners(project_id,user_id) VALUES(10,2),(10,5),(11,2),(12,2);
    INSERT INTO budget_role_assignments(role_key,department,user_id,assigned_by) VALUES('finance_review','',3,1);`);
  function prepare(sql){let values=[];return {bind(...v){values=v;return this;},async first(){return raw.prepare(sql).get(...values)||null;},async all(){return {results:raw.prepare(sql).all(...values)};},async run(){const r=raw.prepare(sql).run(...values);return {meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}};}};}
  let tail=Promise.resolve();
  const env={raw,JWT_SECRET:secret,DB:{prepare,batch(statements){const task=tail.then(async()=>{raw.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());raw.exec('COMMIT');return out;}catch(e){raw.exec('ROLLBACK');throw e;}});tail=task.catch(()=>{});return task;}}};
  await ensureBudgetSchema(env);return env;
}

async function cleanup(env,user,path='',method='GET',body={},headers={}){const token=await signJWT({sub:user},secret);const req=new Request('https://school.test/api/admin/cleanup'+path,{method,headers:{Cookie:'bpd_session='+token,'Content-Type':'application/json',...headers},body:method==='GET'?undefined:JSON.stringify(body)});const response=await handleAdminCleanup(req,env,new URL(req.url).pathname,method);return {status:response.status,body:await response.json()};}
async function mode(env){return (await cleanup(env,1,'/session','POST')).body.token;}
async function preview(env,token,scope,ids){return cleanup(env,1,'/preview','POST',{mode_token:token,scope,ids});}
async function remove(env,token,p){return cleanup(env,1,'/delete','POST',{mode_token:token,preview_token:p.body.preview_token,confirmation:'Avada Kedavra',reason:'ลบข้อมูลทดสอบ'});}
async function seedExpense(env,id=21,status='paid'){await env.DB.prepare("INSERT INTO project_expenses(id,project_id,fiscal_year,expense_date,description,amount,status,created_by,workflow_version,current_step) VALUES(?,10,2570,'2026-10-01','ทดสอบ',100,'draft',2,2,'draft')").bind(id).run();await env.DB.prepare("INSERT INTO budget_request_items(expense_id,line_no,category,description,quantity,unit_price,amount) VALUES(?,1,'materials','ทดสอบ',1,100,100)").bind(id).run();await env.DB.prepare('UPDATE project_expenses SET status=?,current_step=? WHERE id=?').bind(status,status==='paid'?'completed':'finance_queue',id).run();}

test('cleanup is superadmin-only; activation and preview never delete and revoked/other-user tokens fail',async()=>{const env=await fixture();assert.equal((await cleanup(env,2)).status,403);env.raw.exec("UPDATE users SET role='executive' WHERE id=4");assert.equal((await cleanup(env,4,'/session','POST')).status,403);const token=await mode(env);assert.equal((await cleanup(env,1,'/preview','POST',{scope:'projects',ids:[10]})).status,403);const p=await preview(env,token,'projects',[10]);assert.equal(p.status,200);assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM projects').get().n,4);assert.equal((await cleanup(env,4,'/delete','POST',{mode_token:token,preview_token:p.body.preview_token,confirmation:'Avada Kedavra',reason:'ทดสอบ'})).status,403);await cleanup(env,1,'/session','DELETE',{mode_token:token});assert.equal((await remove(env,token,p)).status,403);});
test('paid test request cleanup archives financial ledger and attachments; normal paid protection remains intact',async()=>{const env=await fixture(),token=await mode(env);await seedExpense(env);env.raw.exec("INSERT INTO documents(id,title,department,document_type,uploaded_by) VALUES(33,'เอกสารทดสอบ','academic','หลักฐาน',2);INSERT INTO budget_supporting_documents(expense_id,title,native_document_id,created_by) VALUES(21,'หลักฐาน',33,2);INSERT INTO file_attachments(entity_type,entity_id,object_key,file_name,mime_type,file_size,uploaded_by) VALUES('document',33,'test-key','test.pdf','application/pdf',100,2);INSERT INTO project_workflow_events(token,expense_id,project_id,event_type,message,actor_id) VALUES('event21',21,10,'pay','paid',1);INSERT INTO project_notifications(event_token,user_id,audience) VALUES('event21',2,'owners');");assert.throws(()=>env.raw.prepare('DELETE FROM project_expenses WHERE id=21').run(),/confirmed_payment_locked/);const p=await preview(env,token,'requests',[21]);assert.equal(p.status,200,JSON.stringify(p));assert.equal(p.body.paid_removed,100);assert.equal(p.body.file_count,1);assert.equal((await projectFundingSummary(env,2570)).budgets.find(b=>b.key==='subsidy').spent_amount,100);const result=await remove(env,token,p);assert.equal(result.status,200,JSON.stringify(result));assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM project_expenses').get().n,0);assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM documents').get().n,0);assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM project_notifications').get().n,0);const archive=JSON.parse(env.raw.prepare('SELECT snapshot FROM admin_cleanup_archive').get().snapshot);assert.equal(archive.project_expenses[0].amount,100);assert.equal(archive.file_attachments[0].object_key,'test-key');assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM admin_cleanup_expense_guard').get().n,0);assert.equal(env.raw.prepare("SELECT COUNT(*) n FROM audit_logs WHERE action='test_cleanup'").get().n,1);assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM projects').get().n,4);const summary=(await projectFundingSummary(env,2570)).budgets.find(b=>b.key==='subsidy');assert.equal(summary.spent_amount,0);assert.equal(summary.remaining_amount,1000);await seedExpense(env,22);assert.throws(()=>env.raw.prepare('DELETE FROM project_expenses WHERE id=22').run(),/confirmed_payment_locked/);});
test('stale preview refuses changed ledger; forged confirmation and wildcard scope refuse deletion',async()=>{const env=await fixture(),token=await mode(env);const p=await preview(env,token,'projects',[10]);env.raw.exec("UPDATE projects SET name='เปลี่ยนชื่อแล้ว' WHERE id=10");assert.equal((await remove(env,token,p)).status,409);assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM projects').get().n,4);assert.equal((await preview(env,token,'users',[1])).status,400);assert.equal((await preview(env,token,'projects',[10,10])).status,400);const fresh=await preview(env,token,'projects',[10]);assert.equal((await cleanup(env,1,'/delete','POST',{mode_token:token,preview_token:fresh.body.preview_token,reason:'x',confirmation:'wrong'})).status,400);});
test('project cleanup removes only selected dependency graph and restores other financial balances',async()=>{const env=await fixture(),token=await mode(env);await seedExpense(env,21,'pending');const p=await preview(env,token,'projects',[10]);assert.equal(p.body.reserved_removed,100);assert.equal(p.body.allocation_removed,1000);const result=await remove(env,token,p);assert.equal(result.status,200,JSON.stringify(result));assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM projects').get().n,3);assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM project_owners WHERE project_id=10').get().n,0);assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM project_expenses WHERE project_id=10').get().n,0);assert.ok(env.raw.prepare('SELECT * FROM projects WHERE id=11').get());});
test('concurrent changes during execution roll back archive, deletion and financial bypass',async()=>{const env=await fixture(),token=await mode(env);const p=await preview(env,token,'projects',[10]);const original=env.DB.batch;let inject=true;env.DB.batch=statements=>{if(inject&&statements.some(s=>true)&&statements.length>3){inject=false;env.raw.exec("UPDATE projects SET description='modified during delete' WHERE id=10");}return original(statements);};const result=await remove(env,token,p);assert.equal(result.status,409);assert.ok(env.raw.prepare('SELECT * FROM projects WHERE id=10').get());assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM admin_cleanup_archive').get().n,0);assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM admin_cleanup_expense_guard').get().n,0);});
test('cleanup lists and searches each supported scope with escaped wildcards',async()=>{const env=await fixture(),token=await mode(env);for(const scope of ['requests','projects','leave','tasks','maintenance','income','documents']){const r=await cleanup(env,1,'/records?scope='+scope,'GET',{}, {'X-Cleanup-Token':token});assert.equal(r.status,200,JSON.stringify(r));}const r=await cleanup(env,1,'/records?scope=projects&search=%25','GET',{}, {'X-Cleanup-Token':token});assert.equal(r.body.records.length,0);});
test('new dependent record during execution aborts instead of deleting unarchived records',async()=>{const env=await fixture(),token=await mode(env);const p=await preview(env,token,'projects',[10]);const original=env.DB.batch;env.DB.batch=statements=>{env.raw.exec("INSERT INTO documents(title,department,project_id,uploaded_by) VALUES('เอกสารที่เพิ่มระหว่างลบ','academic',10,2)");return original(statements);};const r=await remove(env,token,p);assert.equal(r.status,409);assert.ok(env.raw.prepare('SELECT * FROM projects WHERE id=10').get());assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM documents').get().n,1);assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM admin_cleanup_archive').get().n,0);});
test('leave, tasks, maintenance, income and documents can be selectively cleared without affecting users',async()=>{const env=await fixture(),token=await mode(env);env.raw.exec("INSERT INTO leave_requests(id,user_id,leave_type,start_date,end_date,reason) VALUES(31,2,'sick','2026-10-01','2026-10-02','ทดสอบลา');INSERT INTO tasks(id,title,created_by) VALUES(32,'งานทดสอบ',1);INSERT INTO task_assignees(task_id,user_id) VALUES(32,2);INSERT INTO maintenance_requests(id,request_no,title,description,category,reported_by) VALUES(33,'MT-TEST','ซ่อมทดสอบ','ทดสอบ','other',2);INSERT INTO budget_income(id,fiscal_year,received_date,source_name,amount,created_by) VALUES(34,2570,'2026-10-01','ทดสอบรายรับ',100,1);INSERT INTO documents(id,title,department,uploaded_by) VALUES(35,'เอกสารทดสอบ','academic',2);");for(const [scope,id,table] of [['leave',31,'leave_requests'],['tasks',32,'tasks'],['maintenance',33,'maintenance_requests'],['income',34,'budget_income'],['documents',35,'documents']]){const p=await preview(env,token,scope,[id]);assert.equal(p.status,200,JSON.stringify(p));assert.equal((await remove(env,token,p)).status,200);assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM '+table+' WHERE id=?').get(id).n,0);}assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM users').get().n,5);assert.equal(env.raw.prepare('SELECT COUNT(*) n FROM task_assignees').get().n,0);});
test('mode belongs to its creator and expires on the server regardless of browser state',async()=>{const env=await fixture(),token=await mode(env);env.raw.exec("UPDATE users SET role='superadmin' WHERE id=4");assert.equal((await cleanup(env,4,'/preview','POST',{mode_token:token,scope:'projects',ids:[10]})).status,403);env.raw.prepare('UPDATE admin_cleanup_sessions SET expires_at=0 WHERE token=?').run(token);assert.equal((await preview(env,token,'projects',[10])).status,403);});
