import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {DatabaseSync} from 'node:sqlite';
import worker from '../src/index.js';
import {generateSalt,hashPassword} from '../src/lib/crypto.js';
import {databaseQuotaResponse} from '../src/lib/database-errors.js';
const provider=kind=>new Error('D1_ERROR',{cause:new Error(`Your account has exceeded D1's free tier daily row ${kind} limit. Upgrade to a paid plan or wait until tomorrow (midnight UTC) to continue.`)});
test('read quota failures return a Thai message and reset at 07:00 Bangkok next day',async()=>{const r=databaseQuotaResponse(provider('read'),new Date('2026-10-01T11:28:00Z'));assert.equal(r.status,503);const d=await r.json();assert.equal(d.code,'DATABASE_DAILY_QUOTA_EXCEEDED');assert.equal(d.reset_at,'2026-10-02T00:00:00.000Z');assert.match(d.error,/07:00/);assert.match(d.error,/2 ตุลาคม 2569/);assert.equal(r.headers.get('Retry-After'),'45120');assert.equal(r.headers.get('Cache-Control'),'no-store');});
test('write quota and cyclic causes are supported; unrelated failures do not become quota errors',async()=>{assert.equal((await databaseQuotaResponse(provider('write')).json()).quota_kind,'write');const e=new Error('failure');e.cause=e;assert.equal(databaseQuotaResponse(e),null);assert.equal(databaseQuotaResponse(new Error('incorrect password')),null);});
function runtime(){const store=new Map(),events=[],calls=[];let response={ok:false,status:503,data:{code:'DATABASE_DAILY_QUOTA_EXCEEDED',error:'quota exhausted',reset_at:new Date(Date.now()+3600000).toISOString()}};const window={parent:null,dispatchEvent:e=>events.push(e)};window.parent=window;const context=vm.createContext({window,document:{createElement:()=>({}),head:{append(){}}},sessionStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},Date,JSON,Error,CustomEvent:class {constructor(type,options){this.type=type;this.detail=options?.detail;}},fetch:async(path,options)=>{calls.push({path,options});return {ok:response.ok,status:response.status,json:async()=>response.data};}});vm.runInContext(readFileSync('public/js/api.js','utf8'),context);return {context,calls,events,store,set:r=>response=r,call:(path,options)=>vm.runInContext(`apiRequest(${JSON.stringify(path)},${JSON.stringify(options||{})})`,context)};}
test('browser quota circuit stops polling, allows explicit login retry, and resumes after successful login',async()=>{const r=runtime();await assert.rejects(r.call('/api/notifications'),/quota exhausted/);assert.equal(r.calls.length,1);assert.ok(r.store.has('school-database-quota'));await assert.rejects(r.call('/api/overview/revision'),/quota exhausted/);await assert.rejects(r.call('/api/project-documents/overview'),/quota exhausted/);assert.equal(r.calls.length,1);r.set({ok:true,status:200,data:{user:{id:1}}});await r.call('/api/auth/login',{method:'POST',body:{email:'test@example.invalid',password:'fixture-password'}});assert.equal(r.store.has('school-database-quota'),false);await r.call('/api/overview');assert.equal(r.calls.length,3);});
test('expired circuit and ordinary errors do not block subsequent requests',async()=>{const r=runtime();r.store.set('school-database-quota',JSON.stringify({error:'expired',reset_at:'2020-01-01T00:00:00Z'}));r.set({ok:false,status:401,data:{error:'incorrect password'}});await assert.rejects(r.call('/api/auth/login',{method:'POST'}),/incorrect password/);assert.equal(r.store.has('school-database-quota'),false);r.set({ok:true,status:200,data:{}});await r.call('/api/notifications');assert.equal(r.calls.length,2);});
test('login routes retain correct credential verification and return provider quota clearly',async()=>{const raw=new DatabaseSync(':memory:');raw.exec(readFileSync('schema.sql','utf8'));const salt=generateSalt(),hash=await hashPassword('valid-fixture-password',salt);raw.prepare("INSERT INTO users(email,full_name,role,password_hash,password_salt) VALUES('login@example.invalid','ครูทดสอบ','teacher',?,?)").run(hash,salt);let exhausted=false;const prepare=sql=>{let args=[];return {bind(...v){args=v;return this;},async all(){return {results:raw.prepare(sql).all(...args)};},async first(){if(exhausted&&sql.includes('password_hash'))throw provider('read');return raw.prepare(sql).get(...args)||null;},async run(){const r=raw.prepare(sql).run(...args);return {meta:{changes:Number(r.changes),last_row_id:Number(r.lastInsertRowid)}};}};};const env={JWT_SECRET:'login-test-secret',DB:{prepare,async batch(list){const out=[];for(const s of list)out.push(await s.run());return out;}}};const login=password=>worker.fetch(new Request('https://school.test/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'login@example.invalid',password})}),env,{});assert.equal((await login('incorrect-password')).status,401);const success=await login('valid-fixture-password');assert.equal(success.status,200);assert.match(success.headers.get('Set-Cookie'),/bpd_session=/);exhausted=true;const blocked=await login('valid-fixture-password');assert.equal(blocked.status,503);assert.equal((await blocked.json()).code,'DATABASE_DAILY_QUOTA_EXCEEDED');});
