import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const c=vm.createContext({});vm.runInContext(fs.readFileSync('public/js/leave-form-export.js','utf8'),c);const e=c.LeaveFormExport;
const r={id:1,leave_type:'personal',reason:'ติดต่อราชการ & <ทดสอบ>',full_name:'ครู ตัวอย่าง',position:'ครู',request_date:'2026-10-06',start_date:'2026-10-07',end_date:'2026-10-07',leave_days:0.5,contact_address:'บ้านพักครู',contact_phone:'0000000000',status:'approved',director_name:'ผู้อำนวยการตัวอย่าง',deputy_name:'รองผู้บริหารตัวอย่าง',reviewer_comment:'เห็นควรอนุญาต',stats:[{type:'sick',previous_count:0,previous_days:0,current_days:0,total_count:0,total_days:0},{type:'personal',previous_count:1,previous_days:1,current_days:0.5,total_count:2,total_days:1.5},{type:'maternity',previous_count:0,previous_days:0,current_days:0,total_count:0,total_days:0}]};
test('the supplied leave form exports fields, a six-column leave statistics table, checker, opinion and permit decision without a Garuda',()=>{
 const m=e.model(r);assert.equal(m.title,'แบบใบลาป่วย ลาคลอดบุตร ลากิจส่วนตัว');assert.match(m.choices[1],/\( \/ \) กิจส่วนตัว/);assert.match(m.period,/0.5 วัน/);assert.match(m.written[2],/6 ตุลาคม 2569/);assert.match(m.decisionChoice,/\( \/ \) อนุญาต/);
 const files=e.docxFiles(r),xml=files['word/document.xml'];assert.match(xml,/ติดต่อราชการ &amp; &lt;ทดสอบ&gt;/);assert.match(xml,/w:gridSpan w:val="2"/);assert.match(xml,/รองผู้บริหารตัวอย่าง/);assert.match(xml,/ผู้อำนวยการตัวอย่าง/);assert(!xml.includes('garuda'));assert.equal(Object.keys(files).length,3);
 const pdf=e.pdfDefinition(r);assert.equal(pdf.pageSize,'A4');assert.equal(pdf.defaultStyle.font,'Sarabun');assert(JSON.stringify(pdf).includes('สถิติการลา'));assert(JSON.stringify(pdf).includes('เบอร์โทรศัพท์ที่สามารถติดต่อได้ 0000000000'));assert(JSON.stringify(pdf).includes('เห็นควรอนุญาต'));
 const pending=e.model({...r,status:'pending',last_leave:{leave_type:'sick',start_date:'2026-10-01',end_date:'2026-10-02',leave_days:2}});assert.match(pending.last,/1 ตุลาคม/);assert.match(pending.lastEnd,/2 วัน/);assert.equal(pending.decisionChoice,'(   ) อนุญาต    (   ) ไม่อนุญาต');
});
