import test from 'node:test';import assert from 'node:assert/strict';
import {solveTimetable} from '../src/lib/timetable-solver.js';
function fixture(){const classes=[1,2,3,4].map(n=>({grade_level:'ป.1',classroom:String(n)}));const assignments=classes.flatMap((c,i)=>[['ไทย',10,2,i+1],['คำนวณ',5,1,i+1],['สุขภาพ',1,1,i+1],['หนูน้อยพอเพียง',1,1,i+1],['อังกฤษ',4,1,5],['สังคม',2,1,i%2?5:6]].map(([subject,periods_per_week,max_per_day,teacher_id])=>({...c,subject,periods_per_week,max_per_day,teacher_id,room_name:''})));return {classes,assignments,periods_per_day:[6,5,5,5,5],keep_existing:true,existing:[],unavailable:[]};}
const options={maxMs:5000,maxNodes:100000};
test('P1 schedules all 92 periods, avoids shared-teacher collisions and reserves learner development',()=>{const input=fixture(),r=solveTimetable(input,options);assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.entries.length,92);const teachers=new Set(),rooms=new Set();for(const e of r.entries){assert(e.period<=input.periods_per_day[e.weekday-1]);const t=[e.teacher_id,e.weekday,e.period].join('|'),c=[e.classroom,e.weekday,e.period].join('|');assert(!teachers.has(t));assert(!rooms.has(c));teachers.add(t);rooms.add(c);}for(const a of input.assignments)assert.equal(r.entries.filter(e=>e.classroom===a.classroom&&e.subject===a.subject&&e.teacher_id===a.teacher_id).length,a.periods_per_week);assert(r.summary.every(c=>c.unfilled===3));});
test('preserves locked lessons, development and avoids teachers in other grades',()=>{const input=fixture();input.existing=[{...input.classes[0],weekday:1,period:1,subject:'ไทย',teacher_id:1,room_name:null},{...input.classes[0],weekday:2,period:6,subject:'ลูกเสือ',teacher_id:1,room_name:null},{grade_level:'ป.3',classroom:'1',weekday:1,period:2,subject:'อังกฤษ',teacher_id:5}];input.unavailable=[{teacher_id:5,weekday:1,period:3}];const r=solveTimetable(input,options);assert(r.ok,JSON.stringify(r));assert(r.entries.some(e=>e.subject==='ไทย'&&e.classroom==='1'&&e.weekday===1&&e.period===1));assert(r.entries.some(e=>e.subject==='ลูกเสือ'));assert(!r.entries.some(e=>e.teacher_id===5&&e.weekday===1&&[2,3].includes(e.period)));});
test('regeneration retains learner development but replaces selected subject slots',()=>{const input=fixture();input.keep_existing=false;input.existing=[{...input.classes[0],weekday:2,period:6,subject:'ชุมนุม',teacher_id:1},{...input.classes[0],weekday:1,period:1,subject:'เก่า',teacher_id:1}];const r=solveTimetable(input,options);assert(r.ok);assert(r.entries.some(e=>e.subject==='ชุมนุม'));assert(!r.entries.some(e=>e.subject==='เก่า'));});
test('rejects overcapacity, duplicate loads and infeasible blocked teachers without partial entries',()=>{for(const modify of [i=>i.assignments[0].periods_per_week=30,i=>i.assignments.push({...i.assignments[0]}),i=>i.unavailable=Array.from({length:5},(_,d)=>Array.from({length:6},(_,p)=>({teacher_id:5,weekday:d+1,period:p+1}))).flat()]){const i=fixture();modify(i);const r=solveTimetable(i,options);assert.equal(r.ok,false);assert.equal(r.entries,undefined);}});
test('bounded search reports inconclusive timeout',()=>{const r=solveTimetable(fixture(),{maxNodes:0});assert.equal(r.ok,false);assert.match(r.errors[0],/ยังสรุปไม่ได้/);});
test('shared specialist rooms cannot collide',()=>{const i=fixture();i.assignments.filter(a=>a.subject==='อังกฤษ').forEach(a=>a.room_name='ห้องภาษา');const r=solveTimetable(i,options);assert(r.ok);const rooms=new Set();for(const e of r.entries.filter(e=>e.room_name)){const k=[e.room_name,e.weekday,e.period].join('|');assert(!rooms.has(k));rooms.add(k);}});
