import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {handleAuto,ensureAutoSchema} from '../src/routes/timetable-auto.js';import {canManageTimetable} from '../src/lib/timetable-permissions.js';
function fixture(){const db=new DatabaseSync(':memory:');db.exec(`CREATE TABLE users(id INTEGER PRIMARY KEY);INSERT INTO users VALUES(1);CREATE TABLE academic_terms(id INTEGER PRIMARY KEY);INSERT INTO academic_terms VALUES(1);CREATE TABLE timetable_plans(id INTEGER PRIMARY KEY,academic_term_id INTEGER,status TEXT,revision INTEGER NOT NULL DEFAULT 0);CREATE TABLE timetable_entries(id INTEGER PRIMARY KEY,plan_id INTEGER,grade_level TEXT,classroom TEXT,weekday INTEGER,period INTEGER,subject TEXT,teacher_id INTEGER,room_name TEXT,UNIQUE(plan_id,grade_level,classroom,weekday,period),UNIQUE(plan_id,teacher_id,weekday,period));INSERT INTO timetable_plans VALUES(1,1,'draft',0);INSERT INTO timetable_entries VALUES(1,1,'ป.2','1',1,1,'อังกฤษ',9,NULL);`);
const env={DB:{prepare(sql){let args=[];return {bind(...a){args=a;return this;},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return {meta:{changes:db.prepare(sql).run(...args).changes}};},runSync(){return db.prepare(sql).run(...args);}};},async batch(statements){db.exec('BEGIN');try{const result=statements.map(s=>s.runSync());db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}}}};
const config={classes:[{grade_level:'ป.1',classroom:'1'}],assignments:[{grade_level:'ป.1',classroom:'1',teacher_id:9,subject:'อังกฤษ',periods_per_week:4,max_per_day:1,room_name:''}],unavailable:[],keep_existing:true,periods_per_day:[6,5,5,5,5]};
const helpers={setup:async()=>new Response(JSON.stringify({classes:config.classes,teachers:[{id:9}]})),plan:async(_e,_t,status)=>db.prepare('SELECT * FROM timetable_plans WHERE status=?').get(status),draft:async()=>db.prepare('SELECT * FROM timetable_plans WHERE id=1').get()};
const call=(path,method,body)=>handleAuto(new Request('https://test/api/timetable/auto/'+path,{method,...(method==='GET'?{}:{body:JSON.stringify(body)})}),env,{id:1},{id:1},'/api/timetable/auto/'+path,method,helpers);
return {db,env,config,call};}
test('preview is read-only and apply stores only selected rooms in draft',async()=>{const {db,env,config,call}=fixture();await ensureAutoSchema(env);const p=await call('preview','POST',{config});assert.equal(p.status,200);const result=await p.json();assert.equal(db.prepare('SELECT COUNT(*) n FROM timetable_entries').get().n,1);const apply=await call('apply','POST',{config,fingerprint:result.fingerprint});assert.equal(apply.status,200);assert.equal(db.prepare('SELECT COUNT(*) n FROM timetable_entries').get().n,5);assert.equal(db.prepare("SELECT subject FROM timetable_entries WHERE grade_level='ป.2'").get().subject,'อังกฤษ');assert.equal(db.prepare('SELECT COUNT(*) n FROM timetable_auto_guard').get().n,0);assert.equal(db.prepare('SELECT config_json FROM timetable_auto_config').get().config_json,JSON.stringify(config));db.close();});
test('stale preview and infeasible solve cannot overwrite the draft',async()=>{const {db,config,call}=fixture();const result=await (await call('preview','POST',{config})).json();db.exec("UPDATE timetable_entries SET subject='ใหม่' WHERE id=1");assert.equal((await call('apply','POST',{config,fingerprint:result.fingerprint})).status,409);const bad={...config,assignments:[{...config.assignments[0],periods_per_week:30}]};assert.equal((await call('apply','POST',{config:bad,fingerprint:result.fingerprint})).status,422);assert.equal(db.prepare('SELECT COUNT(*) n FROM timetable_entries').get().n,1);assert.equal(db.prepare('SELECT subject FROM timetable_entries').get().subject,'ใหม่');db.close();});
test('batch guard rolls all statements back on concurrent revision mismatch',async()=>{const {db,env}=fixture();await ensureAutoSchema(env);await assert.rejects(env.DB.batch([env.DB.prepare("INSERT INTO timetable_auto_guard VALUES('test',CASE WHEN (SELECT revision FROM timetable_plans WHERE id=1)=99 THEN 1 ELSE 0 END)"),env.DB.prepare('DELETE FROM timetable_entries')]));assert.equal(db.prepare('SELECT COUNT(*) n FROM timetable_entries').get().n,1);db.close();});
test('academic membership and administrative roles can manage; unrelated teachers cannot',async()=>{assert(await canManageTimetable({}, {role:'superadmin'}));assert(await canManageTimetable({}, {role:'executive'}));const env=academic=>({DB:{prepare(sql){return {bind(){return this;},async all(){return {results:[{id:1,departments:academic?'academic':'personnel'}]};},async first(){return null;}};}}});assert(await canManageTimetable(env(true),{id:1,role:'teacher'}));assert.equal(await canManageTimetable(env(false),{id:1,role:'teacher'}),false);});
